version: '3'

services:
  vue-app:
    build: .
    ports:
      - "8081:80"
    container_name: vue-nginx
    networks:
      - laravel-app_laravel-vue-app-network

networks:
  laravel-app_laravel-vue-app-network:
    external: true