version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-dev
    volumes:
      - ./app:/app          # Mount your source code
      - /app/node_modules   # Persist container's node_modules
    ports:
      - "5173:5173"         # Vite dev server port
    command: npm run dev -- --host
    networks:
      - laravel-app_laravel-vue-app-network

networks:
  laravel-app_laravel-vue-app-network:
    external: true